# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Run tests'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarCloud'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      sonar.organization=shaolans-github


- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'


